### ISSUE TITLE
error expression

### ISSUE THREAD

**Issue by shixiaomiaomiao** [kaelzhang/tpl#1]
There is an error expression of 'memoize' which should be 'memorize' in the next-to-last row.

**Comment by kaelzhang** [comment]
There is no expression named `memoize`

**Comment by shixiaomiaomiao** [comment]
The word <code>memoize</code> is just in the <code>README.md</code> .

**Comment by kaelzhang** [comment]
Nope. It is exactly MEMOIZE not memorize. See [here](https://en.wikipedia.org/wiki/Memoization)
